name: rss_news_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^8.0.2
  get_it: ^8.0.3
  injectable: ^2.4.1
  flutter_svg: ^2.2.0
  elegant_notification: ^2.5.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  focus_detector: ^2.0.1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.2.0
  hive: ^2.2.3
  keyboard_dismisser: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
  mask_text_input_formatter: ^2.9.0
  rxdart: ^0.27.7
  dio: ^5.4.2+1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.10.0
  auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  freezed: ^2.5.2
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/common/gen
  integrations:
    flutter_svg: true
